# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d144f3efd767bddee77faa8c712ca811926fce60439fb39e3d82635d14213a1e0ff00b423929de0f40bada76e9d71de97da002049cd0c8140c6c31c57b04d917

test:
  secret_key_base: 3742f435c2cf7859e1809039c4a4955cdad706a7d1bcfb85ec61828cccf592919bf8a686a754900846164f765927aaec52f67ffe59958db9b1c244aef36f41d6

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
